name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: prod deployment
    runs-on: ubuntu-latest
    environment:
      name: Production
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm run install-notes-packages
      - name: Serverless Deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./apis/notes && serverless deploy --stage prod"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Integration Tests
        run: npm run test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}