service: sg-notes
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  stage: dev
  region: us-east-1
  environment:
    STAGE: ${self:custom.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    NOTES_TABLE: !Ref NotesTable

package:
  individually: true
  patterns:
    - "!./**"
    - functions/lib/helper.js

custom:
  stage: ${opt:stage, self:provider.stage}
  export-env:
    overwrite: true

functions:
  createNote:
    handler: functions/createNote.handler
    events:
      - http:
          path: notes
          method: post
          request:
            schemas:
              application/json: ${file(schemas/Note.json)}
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt NotesTable.Arn
    package:
      patterns:
        - node_modules/**
        - functions/createNote.js

  updateNote:
    handler: functions/updateNote.handler
    events:
      - http:
          path: notes/{id}
          method: put
          request:
            schemas:
              application/json: ${file(schemas/Note.json)}
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:UpdateItem
        Resource: !GetAtt NotesTable.Arn
    package:
      patterns:
        - functions/updateNote.js

  getNote:
    handler: functions/getNote.handler
    events:
      - http:
          path: notes/{id}
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:GetItem
        Resource: !GetAtt NotesTable.Arn
    package:
      patterns:
        - functions/getNote.js

  deleteNote:
    handler: functions/deleteNote.handler
    events:
      - http:
          path: notes/{id}
          method: delete
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:DeleteItem
        Resource: !GetAtt NotesTable.Arn
    package:
      patterns:
        - functions/deleteNote.js

  getAllNotes:
    handler: functions/getAllNotes.handler
    events:
      - http:
          path: notes
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:Scan
        Resource: !GetAtt NotesTable.Arn
    package:
      patterns:
        - functions/getAllNotes.js

resources:
  Resources: ${file(resources.yml)}

plugins:
  - serverless-iam-roles-per-function
  - serverless-export-env
